name: Push to Public Test Environment

on:
  push:
    tags:
      - current-beta

run-name: Create beta build

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install and Build üîß
        run: |
          npm ci --workspaces --include-workspace-root
          npm run build-beta
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=cluetrainer-beta --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Purge Cloudflare cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          hosts: beta.cluetrainer.app
